[project]
name = "hw-2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pdflatex>=0.1.3",
    "tex-table-and-img>=0.0",
]
